csv_files:
  - path: "../results/hj_pred1.csv"
    weight: 1
  - path: "../results/jw_pred2.csv"
    weight: 1
  - path: "../results/sy_pred.csv"
    weight: 1
  - path: "../results/sm_pred.csv"
    weight: 1
  - path: "../results/JE_pred.csv"
    weight: 0.5